# First Project: Building a Machine Learning Model

In [145]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

In [146]:
new_data = pd.read_csv("delaney_solubility_with_descriptors.csv")
new_data

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
0     2.59540  167.850                0.0            0.000000 -2.180
1     2.37650  133.405                0.0            0.000000 -2.000
2     2.59380  167.850                1.0            0.000000 -1.740
3     2.02890  133.405                1.0            0.000000 -1.480
4     2.91890  187.375                1.0            0.000000 -3.040
...       ...      ...                ...                 ...    ...
1139  1.98820  287.343                8.0            0.000000  1.144
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893
1142  2.56214  354.815                3.0            0.521739 -3.790
1143  2.02164  179.219                1.0            0.461538 -2.581

[1144 rows x 5 columns]

In [147]:
new_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MolLogP             1144 non-null   float64
 1   MolWt               1144 non-null   float64
 2   NumRotatableBonds   1144 non-null   float64
 3   AromaticProportion  1144 non-null   float64
 4   logS                1144 non-null   float64
dtypes: float64(5)
memory usage: 44.8 KB

## Data Preparation

### Separate into x and y

In [148]:
y = new_data['logS']
y

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [149]:
x = new_data.drop('logS', axis=1)
x

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0     2.59540  167.850                0.0            0.000000
1     2.37650  133.405                0.0            0.000000
2     2.59380  167.850                1.0            0.000000
3     2.02890  133.405                1.0            0.000000
4     2.91890  187.375                1.0            0.000000
...       ...      ...                ...                 ...
1139  1.98820  287.343                8.0            0.000000
1140  3.42130  286.114                2.0            0.333333
1141  3.60960  308.333                4.0            0.695652
1142  2.56214  354.815                3.0            0.521739
1143  2.02164  179.219                1.0            0.461538

[1144 rows x 4 columns]

In [150]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

### **Model Building**

#### **Linear Regression**

##### **Training Model**

In [151]:
from sklearn.linear_model import LinearRegression

model_1 = LinearRegression()

model_1.fit(X_train, y_train)

LinearRegression()

##### **Applying the model to make a Prediction**

In [152]:
y_pred_model_train = model_1.predict(X_train)
y_pred_model_test = model_1.predict(X_test)

##### **Evaluate Model Performance**

In [153]:
from sklearn.metrics import mean_squared_error, r2_score

train_model_1_mse = mean_squared_error(y_train, y_pred_model_train)
train_model_1_r2 = r2_score(y_train, y_pred_model_train)

test_model_1_mse = mean_squared_error(y_test, y_pred_model_test)
test_model_1_r2 = r2_score(y_test, y_pred_model_test)

In [154]:
print("Model 1 MSE (Train) : ", train_model_1_mse)
print("Model 1 R2 (Train) : ", train_model_1_r2)
print("Model 1 MSE (Test) : ", test_model_1_mse)
print("Model 1 R2 (Test) : ", test_model_1_r2)

Model 1 MSE (Train) :  1.0075362951093687
Model 1 R2 (Train) :  0.7645051774663391
Model 1 MSE (Test) :  1.0206953660861033
Model 1 R2 (Test) :  0.7891616188563282

In [155]:
Model_1_results = pd.DataFrame(['Linear Regression', train_model_1_mse, train_model_1_r2, test_model_1_mse, test_model_1_r2]).transpose()
Model_1_results.columns = ['Method', 'Train MSE', 'Train R2', 'Test MSE', 'Test R2']

In [156]:
Model_1_results

              Method Train MSE  Train R2  Test MSE   Test R2
0  Linear Regression  1.007536  0.764505  1.020695  0.789162

#### **Random Forest**

##### **Training Model**

In [157]:
from sklearn.ensemble import RandomForestRegressor

model_2 = RandomForestRegressor(max_depth=2, random_state=100)
model_2.fit(X_train, y_train)

RandomForestRegressor(max_depth=2, random_state=100)

##### **Applying the model to make a Prediction**

In [158]:
y_pred_model2_train = model_2.predict(X_train)
y_pred_model2_test = model_2.predict(X_test)

##### **Evaluate Model Prediction**

In [159]:
from sklearn.metrics import mean_squared_error, r2_score

train_model_2_mse = mean_squared_error(y_train, y_pred_model2_train)
train_model_2_r2 = r2_score(y_train, y_pred_model2_train)

test_model_2_mse = mean_squared_error(y_test, y_pred_model2_test)
test_model_2_r2 = r2_score(y_test, y_pred_model2_test)

In [160]:
print("Model 2 MSE (Train) : ", train_model_2_mse)
print("Model 2 R2 (Train) : ", train_model_2_r2)
print("Model 2 MSE (Test) : ", test_model_2_mse)
print("Model 2 R2 (Test) : ", test_model_2_r2)

Model 2 MSE (Train) :  1.028227802112806
Model 2 R2 (Train) :  0.7596688824431413
Model 2 MSE (Test) :  1.407688264904896
Model 2 R2 (Test) :  0.7092230211002489

In [161]:
Model_2_results = pd.DataFrame(['Random Forest', train_model_2_mse, train_model_2_r2, test_model_2_mse, test_model_2_r2]).transpose()
Model_2_results.columns = ['Method', 'Train MSE', 'Train R2', 'Test MSE', 'Test R2']

In [162]:
Model_2_results

          Method Train MSE  Train R2  Test MSE   Test R2
0  Random Forest  1.028228  0.759669  1.407688  0.709223

#### **Ridge Regression**

##### **Training Model**

In [163]:
from sklearn.linear_model import Ridge

model_3 = Ridge(alpha=1.0)
model_3.fit(X_train, y_train)

Ridge()

##### **Applying the model to make a Prediction**

In [164]:
y_pred_model3_train = model_3.predict(X_train)
y_pred_model3_test = model_3.predict(X_test)

##### **Evaluate Model Prediction**

In [165]:
from sklearn.metrics import mean_squared_error, r2_score

train_model_3_mse = mean_squared_error(y_train, y_pred_model3_train)
train_model_3_r2 = r2_score(y_train, y_pred_model3_train)

test_model_3_mse = mean_squared_error(y_test, y_pred_model3_test)
test_model_3_r2 = r2_score(y_test, y_pred_model3_test)

In [166]:
print("Model 3 MSE (Train) : ", train_model_3_mse)
print("Model 3 R2 (Train) : ", train_model_3_r2)
print("Model 3 MSE (Test) : ", test_model_3_mse)
print("Model 3 R2 (Test) : ", test_model_3_r2)

Model 3 MSE (Train) :  1.0075385768540326
Model 3 R2 (Train) :  0.7645046441465397
Model 3 MSE (Test) :  1.0206248056373988
Model 3 R2 (Test) :  0.7891761940677693

In [167]:
Model_3_results = pd.DataFrame(['Ridge Regression', train_model_3_mse, train_model_3_r2, test_model_3_mse, test_model_3_r2]).transpose()
Model_3_results.columns = ['Method', 'Train MSE', 'Train R2', 'Test MSE', 'Test R2']

In [168]:
Model_3_results

             Method Train MSE  Train R2  Test MSE   Test R2
0  Ridge Regression  1.007539  0.764505  1.020625  0.789176

#### **XGBoost and LightGBM**

In [169]:
import xgboost as xgb
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score

# 1. XGBoost Regressor
xgb_model = xgb.XGBRegressor(
    n_estimators=100, 
    max_depth=3, 
    learning_rate=0.1, 
    random_state=100
)
xgb_model.fit(X_train, y_train)
xgb_preds = xgb_model.predict(X_test)

xgb_mse = mean_squared_error(y_test, xgb_preds)
xgb_r2 = r2_score(y_test, xgb_preds)


# 2. LightGBM Regressor
lgb_model = lgb.LGBMRegressor(
    n_estimators=100, 
    max_depth=3, 
    learning_rate=0.1, 
    random_state=100,
    verbose=-1
)
lgb_model.fit(X_train, y_train)
lgb_preds = lgb_model.predict(X_test)

lgb_mse = mean_squared_error(y_test, lgb_preds)
lgb_r2 = r2_score(y_test, lgb_preds)


# 3. Print Results
results = pd.DataFrame({
    'Model': ['XGBoost', 'LightGBM'],
    'MSE': [xgb_mse, lgb_mse],
    'R2 Score': [xgb_r2, lgb_r2]
})

print("=== Model Performance Comparison ===")
print(results.to_string(index=False))

=== Model Performance Comparison ===
   Model      MSE  R2 Score
 XGBoost 0.678393  0.859869
LightGBM 0.680051  0.859526

In [170]:
# Test Predictions
xgb_test_preds = xgb_model.predict(X_test)

# Test Metrics
xgb_test_mse = mean_squared_error(y_test, xgb_test_preds)
xgb_test_r2 = r2_score(y_test, xgb_test_preds)

print("=== XGBoost Test Metrics ===")
print(f"Test MSE : {xgb_test_mse:.4f}")
print(f"Test R2  : {xgb_test_r2:.4f}")

=== XGBoost Test Metrics ===
Test MSE : 0.6784
Test R2  : 0.8599

In [171]:
lgb_test_preds = lgb_model.predict(X_test)

# Test Metrics
lgb_test_mse = mean_squared_error(y_test, lgb_test_preds)
lgb_test_r2 = r2_score(y_test, lgb_test_preds)

print("=== LightGBM Test Metrics ===")
print(f"Test MSE : {lgb_test_mse:.4f}")
print(f"Test R2  : {lgb_test_r2:.4f}")

=== LightGBM Test Metrics ===
Test MSE : 0.6801
Test R2  : 0.8595

In [172]:
Model_4_results = pd.DataFrame(['XGBoost', xgb_mse, xgb_r2, xgb_test_mse, xgb_test_r2]).transpose()
Model_4_results.columns = ['Method', 'Train MSE', 'Train R2', 'Test MSE', 'Test R2']

Model_5_results = pd.DataFrame(['LightGBM', lgb_mse, lgb_r2, lgb_test_mse, lgb_test_r2]).transpose()
Model_5_results.columns = ['Method', 'Train MSE', 'Train R2', 'Test MSE', 'Test R2']

#### **Model Comparison**

In [173]:
model_comparison = pd.concat([Model_1_results, Model_2_results, Model_3_results, Model_4_results, Model_5_results], axis=0)
model_comparison.reset_index(drop=True)

              Method Train MSE  Train R2  Test MSE   Test R2
0  Linear Regression  1.007536  0.764505  1.020695  0.789162
1      Random Forest  1.028228  0.759669  1.407688  0.709223
2   Ridge Regression  1.007539  0.764505  1.020625  0.789176
3            XGBoost  0.678393  0.859869  0.678393  0.859869
4           LightGBM  0.680051  0.859526  0.680051  0.859526

#### **Looking for the best model**

In [175]:
from lazypredict.Supervised import LazyRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd

# 1. Initialize LazyRegressor with mean_squared_error as custom metric
reg = LazyRegressor(
    verbose=0,
    ignore_warnings=True,
    custom_metric=mean_squared_error
)

# 2. Fit models on your existing split data
models, _ = reg.fit(X_train, X_test, y_train, y_test)

# 3. Format custom metric column name and clean the output table
models = models.rename(columns={'mean_squared_error': 'MSE', 'R-Squared': 'R2'})

# 4. Sort models by lowest MSE and select the Top 3
top_3_models = models.sort_values(by='MSE', ascending=True).head(3)

# 5. Print the top 3 models with MSE and R2
print("=== Top 3 Best Models (Sorted by MSE) ===")
print(top_3_models[['MSE', 'R2']])

=== Top 3 Best Models (Sorted by MSE) ===
                            MSE        R2
Model
CatBoostRegressor      0.624746  0.870950
ExtraTreesRegressor    0.625890  0.870714
RandomForestRegressor  0.642887  0.867203